{% set xorg_name = "dmxproto" %}
{% set xorg_category = "proto" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "2.3.1" %}
{% set sha256 = "e72051e6a3e06b236d19eed56368117b745ca1e1a27bdc50fd51aa375bea6509" %}
{% set am_version = "1.15" %} # keep synchronized with build.sh

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 1002
  detect_binary_files_with_prefix: true

requirements:
  build:
    - m2-autoconf  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-libtool  # [win]
    - pkg-config  # [win]
    - pkg-config  # [not win]
    - m2-base  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ stdlib("c") }}          # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
  host:
    - xorg-util-macros

test:
  commands:
    - test -e $PREFIX/include/X11/extensions/dmxproto.h  # [not win]

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Print extension headers'

extra:
  recipe-maintainers:
    - epruesse
    - pkgw
