appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: gHLQpTuspMKDNZ+bIzsogE95R6jxs/g6W6rhKoNms67vjpK9BDRZPj1I7TZLp5iAIMxfTUaZDBK3Koh2nZFhbyjjiRw4E3sO/TTmUSc03FQ9WHYiL6vkcLeGZ3HIDfhaNDcIYrKBHwduxQ0DYTVFIepdoD+lJxRjOXP2UiAw+nmvfheGEpA6zqDX+ywR2uVQvLTpHmKFgMsh1ilc08aLSaWOZlkSwj1j2p8J973IaIN17du+ieeYQt5T/VB8YApir6x8liblcG4zFIZqqSpCk5M1CXtNemxNB4W6jhkUqFs6syANLcu7arL0BwqCOXfX3wQEdo4dam1SHS64hn5ibDjewTdj6BEH+3jrh0gfezPcYJvhvfo8PRNiUxkXbSF59+yReKd+WiHClnS9bIOgOY9xp20nFlZkjIdFcOIknbnaqXr2SJuNKuEqOCwrNvMdJTTJQp59jE+HkVkwXE6UV4/IDc8RukVadH92SVW1iweynpwVEhMJN89eTSwGhNHVJd3vOOLBt6ywfTMZsUHN2JI1/flJbJBqafBqea2Z1Y4en3GYUS0WZXkA75Sgd6yK0FoJyNMcL/fiXAgxVKKV2w5AJ7PAIMb4DSwKGAvdNpigokeRHg+Ba3iP116KtiG9B3LxpH5hgDDkHjQKEZSbqeXMphBQyrN9c1W6laNcMNU=}
