travis:
  secure:
    BINSTAR_TOKEN: ofouBYzX8cHh7TmMrb4v4hKxX6JHTLaZantoG5dABnJPSWjAh0atME+AFZeLvMlmFquNug0JbVQWB5mN6d8CWOsMY70PornQw1gTCMg5+Ma3SitCD9k8zCkVlr9Up5STm1Ho5X5c4EZHzzlih44ew7SqDCP9+ZGQPJonAvXHVGfsXPnxlppnm0V9bfvWaL1VgJ+AuIFiHTvCs+wFiOhKAzcV5YyEhmNUsSQq4WsUirxUpLYiXjDRzFLCX8GIQNaPoqi8ESDZlfXV4NnRMfaW5vZNlMdMljL2G8t7spTHko+x2RFvRCmAZIUOw9s2cU+BK/8RpLdNwqcbyKSGxNrJZyd0m3blvIVByBHIaa1EPGyoKr4104HYy11xgb2Ws/mmubmJ8AU8NwNWC03soye6CySP7QomDBfXx8xP8NkGDrYrx8d4sh3Pe5sRZwsl/IFsdmBbY8ehS9XI4mnMd2oOUDgila/vwBVsej5E1yz3b9yjHK8DImQQHfd0CNELhT7oGk7QfZXOOdC+7s0P/vBTtM3ipzY8GzgwocvC7zGa6MvJe6Nam/HifqiGqmBzovQIUnkN9BQX80JLhypf5MlvIQCCcuHNCAQwR62mDqIPvc6vZy/d6vF5jJ21R/Z7Wvyztyc2qHUF2tLw4eMm5T36tUO62CybquOgqX0Sv0M4qUg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
